<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:macro name="link_2020_extrusion" params="name length">
        <link name="${name}">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 ${length/2}"/>
                <geometry>
                    <box size="0.020 0.020 ${length}"/>
                </geometry>
                <material name="aluminum">
                    <color rgba="0.8 0.8 0.8 1.0"/>
                </material>
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0 0 ${length/2}"/>
                <geometry>
                    <box size="0.020 0.020 ${length}"/>
                </geometry>
            </collision>
        </link>
    </xacro:macro>
</robot>
