controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    dynamixel_controllers:
      type: joint_trajectory_controller/JointTrajectoryController

    dynamixel_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

dynamixel_controllers:
  ros__parameters:
    joints:
      - DynaRotor_To_Dynamixel_J3
      - DynaRotor_To_Dynamixel_J2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0

dynamixel_state_broadcaster:
  ros__parameters:
    joints:
      - DynaRotor_To_Dynamixel_J3
      - DynaRotor_To_Dynamixel_J2